### ISSUE TITLE
eachLike producing overly broad matcher?

### ISSUE THREAD

**Issue by valerie-roske** [pact-foundation/pact-js#108]
I'm seeing various related questions but nothing that gets at what I'm looking for, so here goes.

I'm confused by `eachLike`. I would expect that if I provided `bananas: eachLike('some string')`, then in the pact file I would see `"$.body.bananas[*]": { match: "type" }`. This does not happen currently.

Similarly, if I provided `bananas: eachLike({bar: 'value1'})`, then in the pact file I would see `"$.body.bananas[*].bar": { match: "type" }`. This does happen currently.

In both scenarios there is an additional rule: `"$.body.bananas[*].*": { match: "type" }`.
The result is that if someone changes the key `bar` to `baz`, my test still passes, and I am not receiving the right feedback that my code is now wrong.

In the case where I only want to match an array of strings (and not an array of objects), this matching rule in the pact file doesn't make sense to me. I was expecting that `eachLike` would function exactly the same as `somethingLike` for each element in the array, while at the same time allowing for a flexible number of elements to be in the array.

Is there something I'm misunderstanding or missing here?

**Comment by bethesque** [comment]
It's because of history. I used to think that the `[*].*` rule was more correct, however, I hadn't considered the 'array of strings' case, in which case `[*]` makes more sense.

I've been convinced that we should have just put the `match type` on the parent (bananas) object, as it covers both cases. 

> I was expecting that eachLike would function exactly the same as somethingLike for each element in the array, while at the same time allowing for a flexible number of elements to be in the array.

Yes, that is an excellent description.

> The result is that if someone changes the key bar to baz, my test still passes

This is not the expected behaviour. Type matching is done on the values, not the keys. I don't think it has anything to do with the rules you've mentioned.

I have tried to recreate your issue here:

https://github.com/pact-foundation/pact-ruby-e2e-example/commit/d70ee8e4f1f93ce13fd23e68a3f82359dba3ffcd

All the underlying code for pact-js is ruby (packaged in a standalone executable) so this is the exact code that will be running. As you can see in the build [here](https://travis-ci.org/pact-foundation/pact-ruby-e2e-example/builds/285821805#L1021), if you try to use `baz` instead of `bar`, the test will fail.

**Comment by valerie-roske** [comment]
So I see that the test fails in the example you've produced, and I'm able to run that locally as well and still see the error. I was also able to see that the tests will fail in the pact-js e2e example.

After seeing it working with the e2e example, I realised I need to be chasing down this issue in pact-jvm (because my provider is a Java app).

Removing the [*].* rule produced by the consumer seems to be a workaround for now, which is why I had mentioned it. I thought it might be matching all keys, such that it wouldn't detect new ones being added or changed or removed.

**Comment by mefellows** [comment]
Thanks Valerie. For future reference, that's why we have the issue templates to capture information like the consumer and provider languages - things get more complicated when we cross boundaries and as much as it looks like it could be in the JS library, all that information helps us!

**Comment by bethesque** [comment]
@uglyog the `[*].*` rule doesn't make the jvm do anything funny does it?

**Comment by uglyog** [comment]
@bethesque  Are you referring to the dancing hamsters?

No, that should be fine in the JVM implementation. It mostly won't match anything.
