### ISSUE TITLE
Added interactions not called don't fail the tests

### ISSUE THREAD

**Issue by bbarke** [pact-foundation/pact-js#122]
## Software versions

* **OS**: Ubuntu 16.04
* **Consumer Pact library**: pact-web:4.2.1
* **Provider Pact library**: pact:4.2.1
* **Node Version**: v8.2.1

## Expected behaviour
Interactions that have not been called should cause the tests to fail

## Actual behaviour
The tests do not fail

## Steps to reproduce
See example project here: https://github.com/bbarke/pact-js-example

**Comment by mefellows** [comment]
Thanks, will take a look.

**Comment by mefellows** [comment]
OK, so the problem is a poorly placed [`afterEach` block](https://github.com/bbarke/pact-js-example/blob/master/client-spec.js#L118-L120), which is resetting the expectations (clearing interactions) between successive `it` blocks, obscuring the problem and invalidating the tests!:

```
      afterEach(function () {
        return provider.removeInteractions()
      })
```

That function tells the mock service "OK, we're done with that set of tests, please reset so we can do the next ones". The problem with that thinking, is that we've separated the functional test 'it' block from the 'verification' `it` block, and in between removed any expectations - so the test will always pass.

As you can see, it's not an issue with the framework, just an issue with the example.

I've submitted a PR to your repo to show a failure, and will shortly update our examples as this is just bad practice.

As an aside, I've noticed you have [two](https://github.com/bbarke/pact-js-example/blob/master/client-spec.js#L167-L199) `beforeAll` blocks too which I'm guessing wasn't intentional.

**Comment by mefellows** [comment]
I've updated the Jasmine examples to address this too. Thanks for the report, I can see why it is confusing.

**Comment by bbarke** [comment]
Perfect, thank you for the quick turnaround!
