### ISSUE TITLE
exports is undefined when initialized Pact server with karma-pact

### ISSUE THREAD

**Issue by blackbaud-joshlandi** [pact-foundation/pact-js#137]
when following the example for using karma-pact we're seeing: 

`Uncaught ReferenceError: exports is not defined @pact-foundation/pact/pact-web.js:13`

We're on @pact-foundation/karma-pact v2.1.3 and @pact-foundation/pact v5.3.0.

Note we are initialized the Pact server like:

```
Pact.PactWeb(
{ consumer: 'consumer',
port: 'provider'
})
```
We're pulling pact-web.js from `@pact-foundation/pact` because the example indicates `dist-web/` but that folder doesn't appear to actually exist.

**Comment by blackbaud-joshlandi** [comment]
This also happening on an older version of pact v4.2.1 and karma-pact v2.1.1.  Not sure what's causing it as we've changed nothing.  Perhaps there's an `^` in one of the dependencies in these old versions that's causing a mismatch?

**Comment by mefellows** [comment]
The packages have been moved to the foundation scope for consistency, see the install instructions at https://github.com/pact-foundation/pact-js/blob/master/README.md#using-pact-in-non-node-environments which should be up to date.

I'll take a look later this morning at the examples, if not up to date I'll fix.

The web packages are automatically released so they should be in line with the standard pact package.

**Comment by mboudreau** [comment]
@blackbaud-joshlandi if you could provide an example with your package.json, it would be helpful for us to diagnose the issue.

**Comment by mefellows** [comment]
@blackbaud-joshlandi just getting back to this, here is some more detail for consideration:

> However, it seems I need to run npm install pact-web rather than referencing the file in the pact package. Is there a reason for this? I'm assuming what's available in the pact-web package is a compiled or distributable version while what's in the pact package is not?

As per the [docs](https://github.com/pact-foundation/pact-js/blob/master/README.md#using-pact-in-non-node-environments), this is expected behaviour.

Technically you could probably still reach it from the `pact` package, but it's probably not a safe thing to do - for example, if we ever decide to move `pact-web` into it's own repository or change the release process, it could disappear. 

> Can we count on what's in pact-web to be up-to-date? The fact that it doesn't seem to be listed on npm is off-putting, but if we can count on it to stay current that'd be good to. (It might be the way pact-web is provided through npm is beyond what I understand about npm).

Yes. Both packages are released simultaneously only if all of the tests for both pass. The `pact-web` package is much smaller and has a slightly different interface to `pact`, so they should be under different packages. FWIW the docs are published for [`pact-web`](https://www.npmjs.com/package/@pact-foundation/pact-web) under the foundation now (they weren't before the move as you observed).

> Lastly, it seems I have to explicitly list @pact-foundation/karma-pact in my dependencies, but I would think since @pact-foundation/pact lists it as one of theirs it would install it? It doesn't appear to

Use of `pact-web` doesn't imply that you want to use karma, so we don't include it as a dependency. The `pact` package only includes it as a dev dependency so we can ensure we don't break compatibility with changes (we run CI on all of the examples), so this is why it doesn't come along for the ride.

One thing for our consideration is whether to specify `pact-node` as a dependency from `pact-web`, as it is definitely required, at least as a peer.

cc @mboudreau - do you have any thoughts on this?

**Comment by blackbaud-joshlandi** [comment]
Switching from using the `pact-web.js` that was in the `pact` module to using the module itself appears to have fixed the issue, though i'm still not sure why that issue happened at all.  We changed nothing and were referencing the `pact-web` file in the `pact` module, so i wouldn't expect it to change especially since we're setting specific versions (no use of `^` or `~`).  Regardless, I'm going to go ahead and switch it to `@pact-foundation/pact-web` so it's up to date and works.  

Can probably close the issue as the resolution was using `pact-web` in a different way (referencing the package over the file in `pact`). FWIW, I referenced the version in the `pact` module solely to avoid installing another package.  I tend to try to be conservative with installing packages if I can help it.

**Comment by mefellows** [comment]
Thanks @blackbaud-joshlandi, and sorry again for the confusion.

**Comment by myfashionhub** [comment]
Thank god for this thread. I had to install pact-web package:

```javascript
// package.json
"devDependencies": {
    "pact-web": "4.3.2"
}

// karma.conf.js
files: [
    'node_modules/pact-web/pact-web.js',
]
```

`node_modules/@pact-foundation/pact/pact-web.js` does not handle `exports` properly. I kept getting this error:
```
  Uncaught ReferenceError: exports is not defined
  at node_modules/@pact-foundation/pact/pact-web.js:13
```

**Comment by mefellows** [comment]
@myfashionhub glad you found it then (and sorry to hear of your pain). How do you think we could better improve the docs to help those tripping up on this in the future?
