### ISSUE TITLE
verify Provider with cookies

### ISSUE THREAD

**Issue by katerynae** [pact-foundation/pact-js#163]
Hey guys,

I have an endpoint that requires me to be logged in and have a session id in my cookies.

I created an interaction with cookies that looks like this:
```
const interaction: InteractionObject = {
        state: 'I want to fetch list of all workouts',
        uponReceiving: 'a request to /api/user/user_id/workouts',
        withRequest: {
          method: 'GET',
          path:  '/api/user/user_id/workouts',
          headers: {
            'set-cookie': cookie
          },
        },
        willRespondWith: {
          status: 200,
          headers: {
            'Content-Type': 'application/json',
          },
          body: testWorkoutData,
        },
      };
      return provider.addInteraction(interaction);
    });
```

Then I have a test on provider side that verifies my Pact files in Broker and the response from my server:

```it('verify Pact', (done) => { 
      const opts = {
        providerBaseUrl: 'https://mytestwebsite.com',
        pactUrls: [path.resolve(process.cwd(), './contract_tests/pacts/members-api.json')],
        pactBrokerUsername: 'brokerusername',
        pactBrokerPassword: 'brokerpassword',
      };

      new Verifier().verifyProvider(opts).then(output => {
        console.log('Pact Verification Complete!');
        console.log(output);
        done();
      }).catch((e: any) => {
        console.log('Pact Verification Failed: ', e);
        fail();
        done();
      });
  });
````

But this tests fails because I get 401 'not logged in' error back. It means that cookies are not being sent.

Is there a way to send cookies when verifying the provider? Or I am confusing the whole flow? 

Thank you!

**Comment by mefellows** [comment]
Hi @katerynae, 

We just went through this for [Pact Go](https://github.com/pact-foundation/pact-go/issues/69). I'd recommend reading that first.

In short, yes, this is the wrong way to go about it.

Pact does not have API 'behaviour' built into it. Just because you are sending the `set-cookie` header, doesn't mean the API will be stateful and return you a cookie in the response - you'll need to explicitly set the headers if and when you need them.

Aside from this, however, is an implicit assumption about _state_ in general. The other issue describes the antidote, but i'll leave this request open so you can ask further questions and share with anyone else who comes across this.

**Comment by katerynae** [comment]
Hi @mefellows thank you, looking at it now. I tried to use ```CustomProviderHeaders``` I should have mentioned it. And still got 401 back.

**Comment by katerynae** [comment]
nevermind.. just updated ``` 'set-cookie'``` in my CustomProviderHeaders to ```Cookie``` and it worked. :)

**Comment by mefellows** [comment]
👍 glad to hear, I'll close this off unless you have any further questions.
