### ISSUE TITLE
Getting "an interaction with same description and provider has been used" error

### ISSUE THREAD

**Issue by chris-fa** [pact-foundation/pact-js#187]
This is somewhat confusing so I'll try to describe it the best I can. 

First, I had 1 pact test case set up and working perfectly. The setup was simple (using Jest):

* **beforeAll**: create a `new Pact()` with a port, and mock my api client to use said port
* **afterAll**: call `provider.finalize()`
* **it**: call `provider.addInteraction(interaction)` and `provider.verify()`

Since I want my tests to run parallel I made some little changes, and now I'm getting an error. Here are the changes:

* **beforeEach**: create a `new Pact()` with a port, and mock my api client to use said port. The port is created by a function that basically return port number++, so that they are always different.
* **afterEach**: call `provider.finalize()`
* **it**: call `provider.addInteraction(interaction)` and `provider.verify()`

After the change I always get this error when running the tests the 2nd, 3rd, etc. time:

```
Failed: {"message":"An interaction with same description (\"a user information request\") and provider state (nil) but a different response headers has already been used. Please use a different description or provider state, or remove any random data in the interaction."}
```

I tried deleting the pact file, and the test succeeds only in the first run. Fails on subsequent runs; and also, git shows no change in the pact file.

Note that I only have 1 test case, so there's only 1 pact file with 1 expectation.

## Software versions

* **OS**: `Mac OSX 10.13.3`
* **Consumer Pact library**: `5.9.1`
* **Provider Pact library**: `N/A`
* **Node Version**: `8.11.1`

## Relevant log files

Log file in here: https://pastebin.com/AKVKLXGN

**Comment by mefellows** [comment]
Can you please share you test code? The issue appears to be that your pact test descriptions aren't different enough for pact to be able to write them into the pact file. Also you might want to read thru the troubleshooting guide, it has some strategies for dealing with parallelism

**Comment by chris-fa** [comment]
@mefellows I was able to narrow it down to the following:

```
  willRespondWith: {
    status: 200,
    headers: {
      'Content-Type': 'application/json',    // now it works

      // 'Content-Type': Matchers.regex({
      //   // regext to support receiving charset encoding
      //   generate: 'application/json',
      //   matcher: 'application/json',
      // }),
    },
```

Seems like using a regex for the Content-Type doesn't work.

As you can see in the log file I posted in the description:

Registered
```
"headers": {
      "Content-Type": {
        "json_class": "Pact::Term",
        "data": {
          "generate": "application/json",
          "matcher": {"json_class":"Regexp","o":0,"s":"application/json"}
        }
      }
    },
```

Returned
```
"headers": {
    "Content-Type": {
      "json_class": "Pact::Term",
      "data": {
        "generate": "application/json",
        "matcher": {
          "json_class": "Regexp",
          "o": 0,
          "s": "application/json"
        }
      }
    }
  },
```

**Comment by chris-fa** [comment]
Here's the code:

```
/**
 * @jest-environment node
 */
import { getPort, createPact } from '../helpers';
import { userinfo } from './interactions';

function mockConstantsPort(port) {
  const constants = require('../constants');
  const mockedConstants = { ...constants };

  mockedConstants.BASE_URL = `http://localhost:${port}/api/v1`;

  jest.doMock('../constants', () => mockedConstants);
}

describe('My API', () => {
  let provider;
  let api;

  beforeEach(async () => {
    const port = getPort(); // returns a different valid port each time
    mockConstantsPort(port);

    api = require('./api').default;
    provider = createPact(port); // creates pact with "pactfileWriteMode" to "merged"

    await provider.setup();
  });

  afterEach(() => provider.finalize());

  it('retrieves user information', async () => {
    provider.addInteraction(userinfo);

    const userInfo = await api.getUserInfo();

    expect(userInfo).toEqual({
      firstName: 'John',
      lastName: 'Doe',
    });
    await provider.verify();
  });
});
```

**Comment by mefellows** [comment]
Thanks @chris-fa. The issue is that the `description` and `state` fields must be unique between interactions, and presumably they are not as you are sharing the Interaction (i.e. `import { userinfoInteraction } from './interactions';`). 

The other possibility is that the interaction is left over from previous Pact run, and you should therefore clean the pact directory before running.

Because you are setting the `pactfileWriteMode` to `merge`, Pact is detecting that an existing interaction with the same identifiers are already in the pact, and therefore there is a conflict.

Pact needs to be able to differentiate interactions and it uses these fields to do so.

Does that make sense?

**Comment by chris-fa** [comment]
Hi @mefellows, thanks for the explanation. Theoretically I think I follow what you're saying, it makes sense. However the behavior I'm having goes like this:

I'm running Jest with watch mode, so tests will execute over and over again. If I set the `willRespondWith.headers['Content-Type']` to `application/json`. It works just fine. Even after running several times without quitting, there is no problem; I'm not deleting pact files before running the tests and it still works perfectly.

However, if I set the `willRespondWith.headers['Content-Type']` to a regex that just check that it matches `application/json`, then we see the problem. It doesn't feel like this is related to previous runs at all, nor to conflict in the pact files.

The reason I'm using this regex approach instead of hardcoding `application/json` is because Express sends `application/json; charset=utf-8`. We have reasons not to modify Express default behavior and also reasons not to hardcode the pact with the charset; So a regex is perfect.

The regex approach was working when I was creating the pact in the `beforeAll` method instead of `beforeEach`, which is also weird. I'll try to set up a basic repo tomorrow so that you guys can clone it and verify, if you think this could be helpful.

**Comment by mefellows** [comment]
Cool. I can't look at it this second, but another thing to consider is the regex matching must be in Ruby form (as per the docs).

The regex you provided looks to be invalid (contains an unescaped forward slash). You can check regex style at http://rubular.com/.

**Comment by chris-fa** [comment]
Hey @mefellows, I fixed the regex but that was not the problem ☹️

 I made this repo chris-fa/pactjs-issue-187 to show you the behavior that I'm getting. Hope it helps.

**Comment by chris-fa** [comment]
Hi @mefellows. I made some progress with this issue, and added more code changes. I believe these points are where my confusion lies:

### 1. Parallel tests

When we say parallel tests, I thought every `it` statement was executed in parallel. Seems like that's not the case, but the **files**. I have all my tests in a single file, so I should be treating them as if they're to be be run in series:

- `beforeAll`: creates `new Pact()` instance and call `provider.setup()`
- `afterAll`: call `provider.finalize()`
- `it`: await on `provider.addInteraction` and on `provider.verify()`

**Does this make sense?**

### 2. Contract files

After changes described on the previous point, tests are now passing. There's no crash. However, the last line of the `mockserver-integration.log` file has the error. Maybe I'm supposed to delete the contract every time before the test file runs(?)

Since it's just 1 test file, with 1 `new Pact()` instance, I have only 1 contract file. This contract has all the interactions. One per `it()` test case. 

**Do I have to delete this contract file before creating the `new Pact()` instance, on `beforeAll()`?**

**Comment by mefellows** [comment]
Thanks for the repro @chris-fa, that's much appreciated.

So when you set:

```js
pactfileWriteMode: 'merge',
```

This tells Pact that it will _merge_ in new interactions to an existing file (instead of the default behaviour of just clobbering the file with the new interactions), to allow the behaviour in (1) (where different files can be run in parallel, as you correctly note). 

This mode is really only useful if you need to split tests for _a single consumer-provider pair, across multiple test files_. If they are all part of the same test run, and each file has different parameters for the `new Pact()` clause, then don't set `pactfileWriteMode` and you'll be fine.

So yes, if you use `pactfileWriteMode: 'merge'` this means that you should delete any existing pacts before running the tests.

Does this clear it up? I'll then make sure the README is updated also to make this clearer.

**Comment by chris-fa** [comment]
Thanks a lot, this clears my doubt. I suppose we can close this issue if
you want. I'm all good now! :)

**Comment by mefellows** [comment]
No worries and thanks for your patience.

I'll leave it open so that I can update the docs, hopefully the next person won't suffer the same confusion

**Comment by bethesque** [comment]
The ruby docs say `  -m, [--pact-file-write-mode=PACT_FILE_WRITE_MODE]              # `overwrite` or `merge`. Use `merge` when running multiple mock service instances in parallel for the same consumer/provider pair. Ensure the pact file is deleted before running tests when using this option so that interactions deleted from the code are not maintained in the file.
`

But because of the way the help text is formatted, that text is hidden and you need to scroll to see it. I'll have a think about how to display that better.

**Comment by mefellows** [comment]
True @bethesque, but also I don't expect (or in truth, want) consumers to have to even know that this part of the system exists. I've updated the section in our README and also inline in the code docs block to assist.
