### ISSUE TITLE
i want change for my use

### ISSUE THREAD

**Issue by liangguohun** [pact-foundation/pact-js#284]
## Software versions

* **OS**:  windows 10
* **Consumer Pact library**:   Pact JS v2.6.0
* **pact-foundation/pact-node**:  4.8.3
* **Node Version**: `v10.15.0`

## Expected behaviour
I want to give a `switch` to the addInteraction that when i run the jest test with  --watch
if the pact file change the response can't change too.
now i change the package like so: 
provider.addInteraction(interaction, 'comsumer', 'provider')
that can i can get differ provider and comsumer user the same port and don't stop the mockserver, so
the deverloper can use mock the api 
i also add the process of ctrl+c to stop the mockserver with jest test togethor, and if define the host ip,the ip do not post to  make server, i also change ,expect to merge the change

TBC

## Actual behaviour
if another test change, when i access the api i get the message like：
**Multiple interaction found for GET /**

TBC

## Steps to reproduce

Provide a repository, gist or reproducible code snippet so that we can test the problem.

Consider forking the project and modifying the [E2E test](https://github.com/pact-foundation/pact-go/blob/master/dsl/pact_integration_test.go)

## Relevant log files

Please ensure you set logging to `DEBUG` and attach any relevant log files here (or link from a gist).

**Comment by mefellows** [comment]
Hi @liangguohun thanks for submitting this. I'll be honest, I'm not quite sure what you're asking for.

> that can i can get differ provider and comsumer user the same port and don't stop the mockserver, so the deverloper can use mock the api

If you're not aware already, there is a way to start a mock server in a [stub mode](https://github.com/pact-foundation/pact-node/#stub-servers) (this package is a dependency of Pact JS already) separately to the Pact JS package, which is designed for use in tests such as Mocha/Jest and not in the way you describe. It is designed for use during development to stub out the back end, and can be useful in browser based e2e tests.

Perhaps rather than describing the how to achieve it, you could express simply what you _need_ from a feature perspective.
