### ISSUE TITLE
PactWeb/PactOptions dsl does not match to the deprecated parameters

### ISSUE THREAD

**Issue by hakandilek** [pact-foundation/pact-js#344]
"Passing in consumer/provider to PactWeb is deprecated" as I get as a WARN level log message but on the other hand the relevant typescript dsl is not updated:

https://github.com/pact-foundation/pact-js/blob/4c71dba55511f400e22d2532d38094a9a19c02e3/src/dsl/options.ts#L12

and 

https://github.com/pact-foundation/pact-js/blob/4c71dba55511f400e22d2532d38094a9a19c02e3/src/dsl/options.ts#L15

I think those parameters should be optional.

I've the following in my `devDependencies` if it's any relevant:

```
    "@pact-foundation/karma-pact": "^2.2.0",
    "@pact-foundation/pact": "^9.1.0",
    "@pact-foundation/pact-node": "^9.0.2",
    "@pact-foundation/pact-web": "^9.1.0",
```

**Comment by mefellows** [comment]
Hi @hakandilek, this is by design. The way Pact Web works, we expect some other process to start the mock service in the background - which is the time it should receive the consumer/provider configuration. We don't want  conflicting configurations in it's DSL with another that might start it  separately - it's just an opportunity to create incorrect configurations.

The main Pact library needs those parameters because it is still responsible for  starting that process.

Does this answer your question? Is there a problem it's causing?

**Comment by hakandilek** [comment]
Hi Matt,

I understand the reason why those parameters are deprecated. But I think they should be defined as optional in the type definitions (dsl). If I remove them from my `PactWeb` constructors, ts compiler complains about missing fields/parameters.

Regards,
Hakan

**Comment by mefellows** [comment]
Oh, yes - you're right, we'll get it fixed. (apologies for misunderstanding, I'm going to put it down to the fact that I was awake at 4:30am this morning and brain was yet to fire).

**Comment by anscheinbar** [comment]
Hi, it's still not possible to initialize `PactWeb` with empty options `{}` or no no options at all. You can pass `undefined` as options, but that's just ugly.

Any chance to get a fix for that?

**Comment by mefellows** [comment]
I've just pushed up a branch now. Sorry for the delay (but also, a _really_ easy PR for anybody who actually needed it https://github.com/pact-foundation/pact-js/commit/5a6608622c1f2520f5c84d4497f8109d3103f217).

**Comment by anscheinbar** [comment]
Great, thank you very much!
