### ISSUE TITLE
Optional interactions

### ISSUE THREAD

**Issue by m-radzikowski** [pact-foundation/pact-js#574]
## Issue Classification

- [x] Feature request
- [ ] Bug report

## Feature Request

It looks like if in Consumer test you add multiple Interactions to the Provider, each unit test must call all of them. Otherwise, the test fails.

I don't fully understand the reason for that. The unit test verifies the response, so why does it matter what mock server endpoints were called?

Because of this, I cannot declare a few endpoints at once for related tests. Instead, I have to declare each of them separately, which reduces visibility.

What I aimed to do:

```ts
pactWith({consumer: 'my consumer', provider: 'my provider', pactfileWriteMode: 'merge'}, provider => {
    const client = (): ApolloClient<unknown> => createAppSyncApolloClient(provider.mockService.baseUrl);

    describe('get items by IDs', () => {

            beforeEach(() => Promise.all([
provider.addInteraction(new AppSyncInteraction()
                .given(`items 1 and 2 exist`)
                .uponReceiving('a get items request')
                .withQuery(getItemsQuery)
                .withVariables({
                    ids: [1, 2],
                })
                .willRespondWith(appSyncResponse({
                    body: getItemsResponse,
                })),
provider.addInteraction(new AppSyncInteraction()
                .given(`items 1 and 2 exist`)
                .uponReceiving('a get items request with nonexisting items')
                .withQuery(getItemsQuery)
                .withVariables({
                    ids: [1, 2, 3],
                })
                .willRespondWith(appSyncResponse({
                    body: getItemsResponse,
                }))
            ]));

            it('returns found items', async () => {
                const result = await client().query({
                    query: gql(getItemsQuery),
                    variables: {
                        ids: [1, 2],
                    },
                });

                const data = result.data;
                expect(data.getItems).toBeArrayOfSize(2);
            });

            it('skips not found items', async () => {
                const result = await client().query({
                    query: gql(getItemsQuery),
                    variables: {
                        ids: [1, 2, 3],
                    },
                });

                const data = result.data;
                expect(data.getItems).toBeArrayOfSize(2);
            });

    });
});
```

This results in both tests failed with logs like:

```
W, [2021-01-13T12:40:29.729543 #17781]  WARN -- : Verifying - actual interactions do not match expected interactions. 
Missing requests:
	POST /graphql


W, [2021-01-13T12:40:29.729619 #17781]  WARN -- : Missing requests:
	POST /graphql
```

If I remove one of the interactions, one test passes.

To solve this, I need to put those 2 tests in separate `describe()` blocks (with their own `beforeEach()` initializations), which does not make much sense.

What I think could help, not breaking the current behavior, would be an Interaction flag `optional`, that would make disable checking if this particular interaction was actually called during the test. What do you think about it?

Or maybe I am missing something and this can be already solved in another way?

**Comment by mefellows** [comment]
> I don't fully understand the reason for that. The unit test verifies the response, so why does it matter what mock server endpoints were called?

It should, but it may not. Pact is there to guarantee that it does indeed so what you said it would. It's a mock, not a stub. 

So at a high level, this is the main reason for it.

But zooming out, there is no hard requirement in Pact JS for this to be the case, although it's the default/recommend in our examples. The call to `verify` (which performs this check) can be called at any user defined moment. It just so happens that when using `jest-pact` (the library you've shown to be using) forces this convention.

Unless I'm mistaken, it looks like a feature request for that project in and we should move it there?

**Comment by m-radzikowski** [comment]
Ok, I see now that it happens in the `provider.verify()` call. So instead of calling `verify()` in `afterEach()` we can call only `provider.removeInteractions()` (because normally it is called in `verify()`).

Thank you for the clarification and help. Actually, I was able to override the `afterEach()` from `jest-pack` to not call `verify()` and it works as expected:

```ts
    afterEach(async () => {
        // override default afterEach to not call verify(), only remove interactions from mock server
        await provider.removeInteractions();
    });
```

I think there is no need to implement anything extra in `jest-pact` since the solution is quite easy.

**Comment by TimothyJones** [comment]
Hmm. Of course, you're free to write tests however you like, but I think you might run into problems writing tests this way.

From [the documentation](https://docs.pact.io/getting_started/how_pact_works#consumer-testing), we have this definition of a consumer test:

> assuming the provider returns the expected response for this request, does the consumer code correctly generate the request and handle the expected response?

If you declare all interactions ahead of time, then you can't say which interaction is supposed to be covered by each test. This gives you less certainty about what is tested. Also, if/when you start introducing provider states (where the mock server will return different responses for the same request) you'll get collisions, and will have to change the pattern.

As Matt said, pact (by design) is a mock, not a stub. Pact verifies that you sent what you said you would send. A common question (which it sounds like you might have) is "but why do we need both the mock verification and the unit test?" - the answer is that there are two verifications, with a subtle difference:

1. First, Pact verifies that your client sends what you promised it would, and (if successful) returns the response you defined.
2. Second, your unit test verifies that you are unmarshalling that response correctly. 

In js, usually the second part is trivial since most of the time it is just unmarshalling json. So, the tests can feel a bit silly, because you're `expect`ing that the mock server returned the object you told it to. In other frameworks, you would check that the correct type was produced (and in js where you're not doing a plain unmarshal of a json object the test also is more meaningful).

Anyway, usually, it's a mistake or a misunderstanding to declare more than one interaction at once (there are some exceptions, and they're usually when someone is using graphql, so perhaps that's what is happening here).

It's true that jest-pact expects you to write one test. If you want to write multiple tests for the same interaction, then you could nest them in a describe:

```
let response;
beforeEach(async () => {
   await provider.addInteraction(/* whatever */)
   response = client().query(/* whatever */)
});
describe('the response', () => {
  it("has some property", () => { .... })
  it("has some other property", () => { .... })
});
```
This is a good observation, and I should probably add that to the documentation. 

However, if you can't pull the request out to the `beforeEach` like this, then I would say that it would be better to not define all the interactions together, because they are setup for different tests.

**Comment by m-radzikowski** [comment]
Thank you for a detailed explanation. It makes sense 🙂  I went to back to having separate Interactions defined for each test.

**Comment by mefellows** [comment]
Great response Tim. Perhaps that ought to be extracted into our consumer [best practices guide](https://docs.pact.io/consumer)? It's JS specific, but the key insights are there
