### ISSUE TITLE
[V3] possibility to revert the effect of an interaction in the provider

### ISSUE THREAD

**Issue by individual-it** [pact-foundation/pact-js#597]
### Checklist

Before making a feature request, I have: 

- [x] [Searched the issues to check that this feature hasn't been requested before](https://github.com/pact-foundation/pact-js/issues?q=is%3Aissue)
- [x] Checked the documentation to see if it is possible to do what I want already 

### Feature description

Possibility to run some code after a specific interaction to revert it's effect on the server

### Use case

When running provider side tests, the interactions can have some permanent effect on the server (set values in DB, create files, etc.) other interactions in the same contract might depend on that specific effect not be active/exist

There might be different **views on this problem**:
1. every interaction is responsible to setup the server, so that is in a testable state
    :heavy_plus_sign:  this feature would not be needed
    :heavy_minus_sign: every interaction would be responsible to revert effects of other interactions might have had but would make itself fail
    :heavy_minus_sign: "reversion" need to be allowed to fail because maybe no interaction ran that had that specific effect
    :heavy_minus_sign: potentially an :infinity: number of reversion need to take place
    :heavy_minus_sign: adding a new interaction might break old interactions and code needs to be added to old interactions
2. every interaction is responsible to cleanup after it self. E.g. if an interaction has created a file on the server, it has to delete it afterwards to make sure the next interaction finds the server in a default state.
    :heavy_plus_sign: IMHO that would be better practice for tests
    :heavy_plus_sign: speedup test runs. It's of course possible to reinitialise the complete server on every new interaction, but in complex setups that would take a long time
    :heavy_minus_sign: need changes in pact-js and maybe upstream libs

For no 2 I can see two **possible solutions**:
1. just use the current `given` function e.g. `given('the file is deleted afterwards')` and in the stateHandler check the `setup` variable and if its `false` run cleanup code
   :heavy_plus_sign: there is no problem, no change need to be implemented
   :heavy_minus_sign: ugly naming
2. have a alias to `given` called `after` e.g. `after('delete file')` in the stateHandler the same code is implemented as in solution 1
   :heavy_plus_sign: only very simple code change needed in pact-js
   :heavy_plus_sign: nicer wording than in solution 1
   :heavy_minus_sign: the stateHandler code still has to check `setup` and that might be confusing for readers of the code. Why does the `after` step have a `setup` :question: 
3. make the `after` function call a stateHandler that does not have the `setup` variable
   :heavy_plus_sign: simple clear code in the interactions and handlers
   :heavy_minus_sign: more changes needed in pact-js and maybe in upstream libs (??)

**Comment by TimothyJones** [comment]
This is a super interesting request, and worth bringing up more generally with other pact frameworks.

The "cleanest" ideal is that the provider doesn't know what interactions it is verifying. But, practically, it doesn't work that way, because it has to at least understand the states that are in the contract.

Note that states are not the same as interactions - it's common to use the same state for multiple interactions (eg, "user X exists" might lead to "subscribe user X to Y" or "delete user X", both would require different reversals. And, if you wanted to reverse an interaction, you would also need to know the state ahead of time - since reversing delete user X would be different if user X did not exist to start with).

The way I (and I think most of the core pact maintainers) tend to write provider tests is with the state functions completely replacing the provider state. So, from that perspective, there is no specific reset required. But if you're not mocking the repositories used by the provider, that might be more challenging.

**Comment by TimothyJones** [comment]
As an aside, I think the `setup` boolean would lead to less clarity in tests, and I'd like to see it wrapped by specific handlers:

```
{
   "some state": { setup: () => {....}, teardown: () => { ....} }
}
```

I think it's convenient for rust to call back using the boolean, but we could sugar that out in pact-js.

**Comment by bethesque** [comment]
> every interaction is responsible to cleanup after it self. 

This is not as safe as cleaning before an interaction, as it's tempting to only clean up the data that you expect to be made in the test for the purposes of "efficiency" rather than doing a full reset back to a known state (eg. wiping all the tables). If new functionality is added to an endpoint and suddenly new data is being made, and nobody knows to go and add custom code to clear it out again then you end up with leaky tests.

I always call a "reset" at the start of every provider state set up call (it's easy in the Ruby DSL because there's a "before each", but in JS, I have to manually call the reset() function at the start of each of my provider state handlers.)

**Comment by individual-it** [comment]
@bethesque I totally agree with you that it's saver to make a full reset, its just a trade-off. In my current case that would cost 10-15sec in CI and we test ~160 interactions (more to come) so I can end up with 40min extra CI time per PR
On the other side the effects of the interactions are relatively independent (I know famous last words :wink: ) create user, create a group, create a file etc.

The middle ground for my current project would be not to delete single files but the whole test-user in the app and create a new one on every interaction

**Comment by bethesque** [comment]
I can see why you'd want to be a bit more selective with a clean up that takes that long! 😱 Generating a new user sounds like a smart idea.

There is an issue open to support tear-down in the pact ruby CLI (it's supported in the underlying Ruby impl, just never exposed to pact-js). I assume that would help the situation @TimothyJones ?

**Comment by individual-it** [comment]
BTW: some discussion in slack that kicked off this request: https://app.slack.com/client/T5F60FXSQ/C01BVFCMMK9

**Comment by mefellows** [comment]
```
{
   "some state": { setup: () => {....}, teardown: () => { ....} }
}
```

Is supported in 10.x.x - does this address your needs Artur?

**Comment by individual-it** [comment]
yes, I think this is all we need for now
