### ISSUE TITLE
Workaround for long file path issues on Windows?

### ISSUE THREAD

**Issue by Manish-Giri** [pact-foundation/pact-js#670]
### Software versions

_Please provide at least OS and version of pact-js_

- **OS**: Windows 10
- **Consumer Pact library**: `"pact-node": "~10.11.0"`
- **Provider Pact library**: _e.g. pact-jvm-provider-maven_2.11 v 3.3.8_
- **Node Version**: `10.24.1`

### Issue Checklist

Please confirm the following:

- [ ] I have upgraded to the latest
- [ ] I have the read the FAQs in the Readme
- [ ] I have triple checked, that there are **no unhandled promises** in my code
- [ ] I have set my log level to debug and attached a log file showing the complete request/response cycle
- [ ] For bonus points and virtual high fives, I have created a reproduceable git repository (see below) to illustrate the problem

I just ran into the same issue with Pact errors during `npm run test` due to long folder tree as described [here](https://github.com/pact-foundation/pact-js/issues/237#issuecomment-433591393) in #237. Moving the entire repository over to `C:\Test-Pact` worked, but I can't keep things outside of the Users directory, (example: `C:\Users\JohnDoe`) otherwise our Antivirus setup starts freaking out.

I've also ensured that the `LongPathsEnabled` property in the Windows Registry has been enabled, but this does not seem to have any effect, as reported by other users in the linked issue.

Is there any workaround to this problem? Surely, using "shallow paths" can't be the permanent solution?

**Comment by mefellows** [comment]
> Is there any workaround to this problem? Surely, using "shallow paths" can't be the permanent solution?

It's not. Our [v3 branch](https://github.com/pact-foundation/pact-js#pact-js-v3) will solve that problem, but it's not out of beta yet (it's working, but the interface will change).

I'm not aware of other workarounds, although I'd hope they exist in today's day and age!

**Comment by Manish-Giri** [comment]
@mefellows Okay, thank you!!

**Comment by TimothyJones** [comment]
Some extra context - the problem exists because pact-js delegates to the Ruby pact core binaries, and there is a long-standing bug with long paths in Ruby. When searching for the issue to link to, I found it has (just) been fixed: https://github.com/ruby/ruby/pull/4505

To get Windows long file support with the ruby binaries, we'll need to wait for the fix to be released, and then we'll need a version of Travelling Ruby (which packages the Ruby binaries cross-platform) which supports the future version of Ruby.

As Matt says, the next major release of Pact-JS will work around this problem by using the Rust pact core instead (which brings several other improvements).

**Comment by mefellows** [comment]
Closing. 10.x.x removes this problem.
