### ISSUE TITLE
[V3] Set the Pact specification to use for Pact files generation

### ISSUE THREAD

**Issue by dernat71** [pact-foundation/pact-js#719]
### Checklist

Before making a feature request, I have: 

- [🟢 ] [Searched the issues to check that this feature hasn't been requested before](https://github.com/pact-foundation/pact-js/issues?q=is%3Aissue)
- [🟢 ] Checked the documentation to see if it is possible to do what I want already 

### Feature description

In the context of consumer contract generation, it would be interesting to be able to set the specification version to be used.

### Use case

To bring more flexibility in the verification tooling. An example would be consumers being written in JS (with the latest v3 specs) and producers being written/verified in Python (with pact-python currently only supporting v2 specs).

**Comment by TimothyJones** [comment]
You can do this already. At the moment, the main release only supports v2.

However, if you’re using the beta branch you can import v2 Pact as normal, or you can import from pact/v3 for the ability to generate v3 pacts
 (Apologies, I’m on mobile, otherwise I’d link the examples).

When we release, I’d like to be able to keep much of the same interface from V2 for V3. This would make switching easier.

**Comment by mefellows** [comment]
You can't do it on the v3 branch at the moment, so I'll update this ticket assuming that's the reques

Also, there is this bug in the current branch:

<img width="1078" alt="Screen Shot 2021-08-07 at 8 26 22 am" src="https://user-images.githubusercontent.com/53900/128576799-0ac8c25a-a1d6-47c5-9c2a-013b9a6dcfe4.png">

**Comment by mefellows** [comment]
Closing as 10.x.x now supports this.
