### ISSUE TITLE
Issue serializing Set<string>  

### ISSUE THREAD

**Issue by Daniel-Kempf** [pact-foundation/pact-js#720]
### Software versions

- **OS**: Ubuntu 21.04
- **Consumer Pact library**: Pact JS 9.16.0 used with typescript 4.3.5
- **Node Version**: v16.4.1

### Issue Checklist

Please confirm the following:

- [x] I have upgraded to the latest
- [x] I have the read the FAQs in the Readme
- [x] I have triple checked, that there are **no unhandled promises** in my code and have [read](https://github.com/pact-foundation/pact-js/#test-fails-when-it-should-pass) the section on intermittent test failures
- [ ] I have set my log level to debug and attached a log file showing the complete request/response cycle
- [ ] For bonus points and virtual high fives, I have created a reproduceable git repository (see below) to illustrate the problem

### Expected behaviour

```
"body": {
          "id": "00000000-0000-0000-0000-000000000001",
          "colors": ["red"],   
        },
```

### Actual behaviour
```
"body": {
          "id": "00000000-0000-0000-0000-000000000001",
          "colors": {
          }
        },
 ```

### Steps to reproduce

When I run pact tests i get wrong json output file as showed in actual behaviour.
Following my test case is attached:

 ```
describe('Vehicle Endpoint', () => {
    test('it returns a vehicle', () => {
      const expectedResponse: VehicleResponse = {
        id: vehicleId,
        colors: new Set<string>(['red']),
      }
      return pact
        .addInteraction({
          state: 'vehicle 1',
          uponReceiving: 'a request to get vehicle 1',
          withRequest: {
            method: 'GET',
            path: '/vehicles/' + vehicleId,
          },
          willRespondWith: {
            status: 200,
            headers: { 'Content-Type': 'application/json' },
            body: like(expectedResponse),
          },
        })
        .then(() => {
          return client.getVehicle(vehicleId).then((response: VehicleResponse) => {
            expect(response.id).toEqual(expectedResponse.id)
          })
        })
    })
```

**colors: new Set<string>(['red']),** defines colors of vehicle. When i pass **['red'] as any as Set<string>** it works fine.
For me it seems that Set is serialized the wrong way, because an empty object is returned in pact output file.

**Comment by TimothyJones** [comment]
In the interaction, you're describing the JSON that will be on the wire. `Set` isn't a valid JSON type.

When you do`['red'] as any as Set`, you're passing an array but telling the compiler it's a `Set` (which it isn't - you can see that this is a mistake, because the compiler won't let you do `['red'] as Set`). The compiler doesn't mind being passed something it thinks is a `Set`, because in the current release the signature accepts `any`.

We're introducing more specific types in the next version so that the usage is clearer.

**Comment by TimothyJones** [comment]
```
JSON.stringify(new Set(['red'])) // This returns "{}"
```

**Comment by TimothyJones** [comment]
You might be wondering why we don't convert to something sensible (like the array you were expecting) by default - it's because there's not a clear way to distinguish at deserialisation time. How would we be able to tell the difference between the `Set` and an array in `JSON.parse()`?

This is a problem that's wider than Pact. Proposals to add easy JSON mappings to ECMAScript for the `Set` and `Map` types [have been rejected](https://github.com/DavidBruant/Map-Set.prototype.toJSON/issues/16), because it's not easy to do so without forcing developers to write their own implementations at either side (after all, JSON isn't just used by javascript - so if custom logic were added to serialise built-in JS classes, then you can't be certain the other side can deserialise). 

If you control both sides, and you're using JS/TS on both sides, then you might be interested in something like [the `serialise-javascript` package](https://www.npmjs.com/package/serialize-javascript), which defines additional mappings to support the serialisation / deserialisation of `Set`/ `Map` and a whole host of other types.

If you don't control both sides, then you'll need to make sure that you are serialising your `Set` to an array before making the API call (it is possible that your API framework is already doing this for you). 

Either way, you'll need to use the an appropriate JSON expectation in your `addInteraction` call, which unfortunately can't be a `Set`.

I'm going to close this for now, please feel free to comment asking for further clarification if you need. Please reopen this issue if you think I closed it in error.

**Comment by mefellows** [comment]
Thanks for that detailed response Tim!

**Comment by Daniel-Kempf** [comment]
Also thanks from my side for your detailed answer!
