### ISSUE TITLE
error verifying Pact: "error: Found argument '--broker-token' which wasn't expected, or isn't valid in this context

### ISSUE THREAD

**Issue by DmitriyDmitruk** [pact-foundation/pact-js#738]
error verifying Pact: "error: Found argument '--broker-token' which wasn't expected, or isn't valid in this context
**when running verify-pacts.ts**

### Software versions

- **Provider Pact library**: Pact JS **10.0.0-beta.45**
- **OS**: Windows 10 build 19042.1110
- **Node Version**: 14.17.5
- **NPM Version**: 7.21.1

**verify-pacts.ts**
![Screenshot_115](https://user-images.githubusercontent.com/17577713/133244485-b09d02aa-c9f3-4e7b-bdc2-f18000710d8f.jpg)

**error**
![Screenshot_116](https://user-images.githubusercontent.com/17577713/133245194-c2664f18-23b5-41ea-8fe4-041aba5a6ee4.jpg)

**Comment by TimothyJones** [comment]
Thanks for the report! We'll get a fix out asap.

In the meantime, a workaround could be to use the environment variable `PACT_BROKER_TOKEN` (set before calling the Verifier).

**Comment by DmitriyDmitruk** [comment]
@TimothyJones Thank you for efficiency!

**Comment by TimothyJones** [comment]
v10.0.0-beta.47 is released with this fixed.

**Comment by mefellows** [comment]
Tim, I ran into a similar problem this morning. Wondering if our "crash reporter" should print out the relevant environment variables that are set?

I went to run the tests and they failed, as it turned out, because I had a bunch of env vars there that made them talk to a broker (which conflicted with explicit args in the JS test).

**Comment by TimothyJones** [comment]
Yeah, I think as part of #602 we should warn if explicit args conflict with env vars (and tell the user which one is being applied).

Although, setting the wrong environment shouldn't cause a crash. I'd prefer if the ffi didn't listen to env variables so that pact-js (and other consumers) had to pass them explicitly.

**Comment by DmitriyDmitruk** [comment]
@TimothyJones Tell me please, why Verifier is sending request to http://localhost:55327/
**but not to the url I've defined in `providerBaseUrl` option ?**

![Screenshot_117](https://user-images.githubusercontent.com/17577713/133394224-dc034cd7-137c-418b-a358-b9625f3e015a.jpg)

**Comment by mefellows** [comment]
The verification calls pass through an internal proxy created by Pact. That is the dynamic address - is it causing problems?

**Comment by DmitriyDmitruk** [comment]
So this is not the address where Pact sending real request to the provider?
