### ISSUE TITLE
Running pact with a mock server that is binding to other than localhost fails to start

### ISSUE THREAD

**Issue by lirantal** [pact-foundation/pact-js#86]
## Software versions

* **OS**: e.g. Mac OSX 10.11.5
* **Consumer Pact library**: e.g. Pact JS v2.6.0
* **Node Version**: 7.10

## Expected behaviour

As the consumer side, running the pact mock server with host set to an IP address other than localhost/127.0.0.1 should start the server normally

## Actual behaviour

The pact server seems to start but nothing shows up in the logs (set to DEBUG) and the mocked server isn't responsive.

## Steps to reproduce

```
const provider = pact({
  consumer: 'a',
  provider: 'b',
  host: '192.168.1.2',
  port: 6000,
  log: path.resolve(process.cwd(), 'logs', 'pact.log'),
  dir: path.resolve(__dirname, 'pacts'),
  logLevel: 'DEBUG',
  spec: 2
})
```

## Relevant log files

Please ensure you set logging to `DEBUG` and attach any relevant log files here (or link from a gist).

**Comment by bethesque** [comment]
I believe the host is passed to the mock service to tell it where to bind. I think this is the code here: https://github.com/pact-foundation/pact-node/blob/02e582fae322289241af48d61f7283918a2d508e/src/server.js#L51

You'll only be able to bind the mock service to localhost, 127.0.0.1 or 0.0.0.0. The problem is, if you want to then access that mock service via a non-localhost IP, there is no separate configuration to do that.

**Comment by bethesque** [comment]
What problem are you trying to solve?

**Comment by lirantal** [comment]
Problem solved then, indeed the bind-all of 0.0.0.0 works just fine.
@mefellows I need to have the mock service running not on localhost but actually be available on a real IP for containers communication to it.

Thanks!

**Comment by lirantal** [comment]
@mefellows I created this PR that would've made it easy for me to figure out the problem cause I did look into those docs.

Would be great if you can merge for others in the future: https://github.com/pact-foundation/pact-node/pull/43

**Comment by mefellows** [comment]
To ready, thanks @lirantal
