### ISSUE TITLE
[V3] publishVerificationResult always pushes the contract to the broker even it set as false

### ISSUE THREAD

**Issue by harris-linktree** [pact-foundation/pact-js#893]
`publishVerificationResult` always pushes the contract to the broker even if it is set as `false`. However, V2, config works as expected.

### Software versions

- **Consumer Pact library**: 10.0.0-beta.60
- **Provider Pact library**: 10.0.0-beta.60
- **Node Version**: node18:Slim docker
### Issue Checklist

Please confirm the following:

- [ ] I have upgraded to the latest
- [ ] I have the read the FAQs in the Readme
- [ ] I have triple checked, that there are **no unhandled promises** in my code and have [read](https://github.com/pact-foundation/pact-js/#test-fails-when-it-should-pass) the section on intermittent test failures
- [ ] I have set my log level to debug and attached a log file showing the complete request/response cycle
- [ ] For bonus points and virtual high fives, I have created a reproduceable git repository (see below) to illustrate the problem

### Expected behaviour

When I set `publishVerificationResult` to false, it should not upload contracts to the broker 

### Actual behaviour

When I set `publishVerificationResult` to false, it uploads contracts to the broker 

### Steps to reproduce

1. config option publishVerificationResult set to `true` and run test to confirm pact uploaded
2. config option publishVerificationResult set to `false` and run test to confirm pact uploaded or not

**Comment by TimothyJones** [comment]
@mefellows: Since this was my code, I'll add some context. I believe this issue is in the Rust verifier.

The argument is mapped here:

https://github.com/pact-foundation/pact-js-core/blob/master/src/verifier/argumentMapper/arguments.ts#L90

The flag mapper is here:

https://github.com/pact-foundation/pact-js-core/blob/master/src/verifier/argumentMapper/index.ts#L71

And the definition of the argument in the rust source is here:

https://github.com/pact-foundation/pact-reference/blob/master/rust/pact_verifier_cli/src/args.rs#L160

My understanding at the time of implementing the argument mapper was that the Verifier CLI treats all booleans as false by default. If the Verifier CLI is updated to support `--no-publish` or `--publish=false`, then [here](https://github.com/pact-foundation/pact-js-core/blob/master/src/verifier/argumentMapper/index.ts#L71
) is where the corresponding change in pact-js would go.

**Comment by mefellows** [comment]
Thanks for raising Harris and for that context Tim. Should be an easy one to squash in the next week.

I'm traveling at the moment in the US so likely I won't be able to get to this until next week

**Comment by mefellows** [comment]
This should be fixed in the latest release (v10.0.1) - can you please check?

**Comment by harris-linktree** [comment]
> This should be fixed in the latest release (v10.0.1) - can you please check?

yeap it is fixed thanks Matt :)

**Comment by mefellows** [comment]
Great, thanks for confirming!
