### ISSUE TITLE
includeWipPactsSince cant be `undefined`

### ISSUE THREAD

**Issue by dimkin-eu** [pact-foundation/pact-js#939]
### Software versions

_Please provide at least OS and version of pact-js_

- **Node Version**: `16`

### Issue Checklist

Please confirm the following:

- [x] I have upgraded to the latest
- [x] I have the read the FAQs in the Readme
- [x] I have triple checked, that there are **no unhandled promises** in my code and have [read](https://github.com/pact-foundation/pact-js/blob/master/docs/troubleshooting.md#test-fails-when-it-should-pass) the section on intermittent test failures
- [x] I have set my log level to debug and attached a log file showing the complete request/response cycle
- [ ] For bonus points and virtual high fives, I have created a reproduceable git repository (see below) to illustrate the problem

### Expected behaviour

this must work
```
includeWipPactsSince: isCI ? new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString().split("T")[0] : undefined,
```

### Actual behaviour

TypeError: includeWipPactsSince

### Steps to reproduce

I've just ( tried to ) upgrade from `9.17.3` to `10.1.2`  and having `TypeError: includeWipPactsSince`

Reporting this issue per @mefellows request from slack

**Comment by TimothyJones** [comment]
Why do you expect that to work? What would `includeWipPactsSince: undefined` mean?

I don't think this is a bug.

**Comment by TimothyJones** [comment]
If you want a way to only specify includeWipPactsSince based on a variable, this is more idiomatic:

```
...(isCI ? { includeWipPactsSince: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString().split("T")[0] } : {})
```

**Comment by dimkin-eu** [comment]
`types.d.ts` asks for string `includeWipPactsSince?: string;`

**Comment by TimothyJones** [comment]
```
includeWipPactsSince?: string;
```

What about this makes you think it can be undefined? This says you may have `includeWipPactsSince`, and if you do, it must be a string. 

This has not changed since 9.x - see the [old definition here](https://github.com/pact-foundation/pact-js-core/blob/pact-node/src/verifier.ts#L340).

See the [discussion in slack](https://pact-foundation.slack.com/archives/C9VBGLUM9/p1661902278150079?thread_ts=1661847291.582479&cid=C9VBGLUM9) for more information. I suspect the break is actually in your typescript options.

**Comment by mefellows** [comment]
Closing as won't fix.
