### ISSUE TITLE
PACT CRASHED

### ISSUE THREAD

**Issue by ghsouza89** [pact-foundation/pact-js#971]
_Thank you for reporting a bug! We appreciate it very much. Issues are a big input into the priorities for Pact development_

_All italic text in this template is safe to remove before submitting_

_Thanks again!_

### Software versions

_Please provide at least OS and version of pact-js_

- **OS**: Windows 11 Home Single Language
- **Pact Node version**: 10.1.4
- **Node Version**: v14.18.0

### Issue Checklist

Please confirm the following:

- [X] I have upgraded to the latest
- [X] I have the read the FAQs in the Readme
- [X] I have triple checked, that there are **no unhandled promises** in my code
- [ ] I have set my log level to debug and attached a log file showing the complete request/response cycle
- [ ] For bonus points and virtual high fives, I have created a reproduceable git repository (see below) to illustrate the problem

### Expected behaviour

No error message should be displayed

### Actual behaviour

`[2022-11-08 20:43:00.007 +0000] ERROR (21300 on Ghsouza): pact-core@13.11.0: !!!!!!!!! PACT CRASHED !!!!!!!!!
                                                                                                                                                       
The pact consumer core returned false at 'withResponseHeader'. This
should only happen if the core methods were invoked out of order

This is almost certainly a bug in pact-js-core. It would be great if you could
open a bug report at: https://github.com/pact-foundation/pact-js-core/issues
so that we can fix it.

There is additional debugging information above. If you open a bug report,
please rerun with logLevel: 'debug' set in the VerifierOptions, and include the
full output.

SECURITY WARNING: Before including your log in the issue tracker, make sure you
have removed sensitive info such as login credentials and urls that you don't want
to share with the world.

We're sorry about this!`

### Steps to reproduce

_How can someone else reproduce this bug?_

1. clone this repo >>> https://github.com/Ghsouza1/poc-contract-testing
2. got to test folder
3. run: npm install
4. npm run test

_For extra bonus points and internet karma, provide a repository, gist or reproducible code snippet so that we can test the problem._

repo: https://github.com/Ghsouza1/poc-contract-testing

_We recommend forking the project and modifying a relevant example [in the examples folder](https://github.com/pact-foundation/pact-js/blob/master/examples)_

### Relevant log files

_Please ensure you set logging to `DEBUG` and attach any relevant log files here (or link to a gist)._
![image](https://user-images.githubusercontent.com/104024271/200671978-49e544bf-0b72-4e61-99ee-f73e5684e89a.png)

**Comment by animeshkumar29** [comment]
Hi Team 
Noticed this issue in my Environment also , can someone please help to resolve this issue or help with some work around , 
Main problem is i have created Pact Setup and Pact interaction method dynamically and when i am calling with single test its passing without any issue , but when i am calling with two test , my first test is passing and my Second test is failing , 

Adding implementation code and Error response 
**Implantation Code** 
`const pactConfig = {
    consumer: 'YourConsumer',
    provider: 'YourProvider',
    port: 1234,
    log: './logs/pact.log',
    dir: './pacts', 
};

const pact = new Pact(pactConfig);
export async function startPactServer() {
    await pact.setup();

}
export async function intractPactServer(state:string,uponReceiving:string,method:HTTPMethods,statusCode:number,resource:string,filePath:string) {
    await pact.addInteraction({
        state: state, 
        uponReceiving: uponReceiving,
        withRequest: {
            method: method,
            path: resource,
        },
        willRespondWith: {
            status: statusCode,
            body: await nilgirihub.readJSONfile(filePath),
        },
    });
}

export async function stopPactServer() {
    await pact.finalize();
}`
**Error** 
`[02:40:10.061] ERROR (2669): pact-core@14.3.6: !!!!!!!!! PACT CRASHED !!!!!!!!!

The pact consumer core returned false at 'uponReceiving'. This
should only happen if the core methods were invoked out of order

This is almost certainly a bug in pact-js-core. It would be great if you could
open a bug report at: https://github.com/pact-foundation/pact-js-core/issues
so that we can fix it.

There is additional debugging information above. If you open a bug report, 
please rerun with logLevel: 'debug' set in the VerifierOptions, and include the
full output.

SECURITY WARNING: Before including your log in the issue tracker, make sure you
have removed sensitive info such as login credentials and urls that you don't want
to share with the world.

We're sorry about this!

[02:40:10.062] ERROR (2669): pact-core@14.3.6: !!!!!!!!! PACT CRASHED !!!!!!!!!

The pact consumer core returned false at 'given'. This
should only happen if the core methods were invoked out of order

This is almost certainly a bug in pact-js-core. It would be great if you could
open a bug report at: https://github.com/pact-foundation/pact-js-core/issues
so that we can fix it.

There is additional debugging information above. If you open a bug report, 
please rerun with logLevel: 'debug' set in the VerifierOptions, and include the
full output.

SECURITY WARNING: Before including your log in the issue tracker, make sure you
have removed sensitive info such as login credentials and urls that you don't want
to share with the world.

We're sorry about this!

[02:40:10.062] ERROR (2669): pact-core@14.3.6: !!!!!!!!! PACT CRASHED !!!!!!!!!

The pact consumer core returned false at 'withRequest'. This
should only happen if the core methods were invoked out of order

This is almost certainly a bug in pact-js-core. It would be great if you could
open a bug report at: https://github.com/pact-foundation/pact-js-core/issues
so that we can fix it.

There is additional debugging information above. If you open a bug report, 
please rerun with logLevel: 'debug' set in the VerifierOptions, and include the
full output.

SECURITY WARNING: Before including your log in the issue tracker, make sure you
have removed sensitive info such as login credentials and urls that you don't want
to share with the world.

We're sorry about this!

[02:40:10.062] ERROR (2669): pact-core@14.3.6: !!!!!!!!! PACT CRASHED !!!!!!!!!

The pact consumer core returned false at 'withStatus'. This
should only happen if the core methods were invoked out of order

This is almost certainly a bug in pact-js-core. It would be great if you could
open a bug report at: https://github.com/pact-foundation/pact-js-core/issues
so that we can fix it.

There is additional debugging information above. If you open a bug report, 
please rerun with logLevel: 'debug' set in the VerifierOptions, and include the
full output.

SECURITY WARNING: Before including your log in the issue tracker, make sure you
have removed sensitive info such as login credentials and urls that you don't want
to share with the world.

We're sorry about this!

[02:40:10.063] ERROR (2669): pact-core@14.3.6: !!!!!!!!! PACT CRASHED !!!!!!!!!

The pact consumer core returned false at 'withResponseBody'. This
should only happen if the core methods were invoked out of order

This is almost certainly a bug in pact-js-core. It would be great if you could
open a bug report at: https://github.com/pact-foundation/pact-js-core/issues
so that we can fix it.

There is additional debugging information above. If you open a bug report, 
please rerun with logLevel: 'debug' set in the VerifierOptions, and include the
full output.

SECURITY WARNING: Before including your log in the issue tracker, make sure you
have removed sensitive info such as login credentials and urls that you don't want
to share with the world.

We're sorry about this!`

**Comment by mefellows** [comment]
See above workaround. Use the newer V3 or V4 interface
